### ISSUE TITLE
doesn't compile with 8.10.2

### ISSUE THREAD

**Issue by teto** [erebe/greenclip#93]
greenclip is currently broken on nixos because they bumped thedefault ghc to 8.10.2 with
```
Building executable 'greenclip' for greenclip-3.3.0..
[1 of 2] Compiling Clipboard        ( src/Clipboard.hs, dist/build/greenclip/greenclip-tmp/Clipboard.o )

src/Clipboard.hs:11:1: error:
    Could not find module ‘Unsafe’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
11 | import           Unsafe                   (unsafeIndex)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

note: keeping build directory '/tmp/nix-build-greenclip-3.3.0.drv-1'
error: --- Error --------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix-build
builder for '/nix/store/vik7gcwyd34jxznc0snc93cj0nkzxzv6-greenclip-3.3.0.drv' failed with exit code 1; last 10 log lines:
  Building executable 'greenclip' for greenclip-3.3.0..
  [1 of 2] Compiling Clipboard        ( src/Clipboard.hs, dist/build/greenclip/greenclip-tmp/Clipboard.o )
  
  src/Clipboard.hs:11:1: error:
      Could not find module ‘Unsafe’
      Use -v (or `:set -v` in ghci) to see a list of the files searched for.
     |
  11 | import           Unsafe                   (unsafeIndex)
```

**Comment by erebe** [comment]
Will take a look at it next week

**Comment by erebe** [comment]
Uploaded a new version on hackage, it should be good with ghc 8.10.2.
Let me know if it is not the case

**Comment by teto** [comment]
thanks will test over the weekend

**Comment by erebe** [comment]
feel free to re-open the issue, if it does not fix the compilation with ghc 8.10.2
